# Sorting, Aggregation & `groupby()`

Use this sample DataFrame for the examples below:

In [62]:
import pandas as pd

df = pd.DataFrame({
    "customer": ["Amit", "Ravi", "Priya", "Neha", "Rahul", "Kiran", "Vikas", "Pooja"],
    "city": ["Jodhpur", "Jaipur", "Delhi", "Mumbai", "Jodhpur", "Delhi", "Jaipur", "Mumbai"],
    "category": ["Laptop", "Mobile", "Laptop", "Tablet", "Mobile", "Laptop", "Tablet", "Mobile"],
    "quantity": [2, 3, 1, 4, 2, 1, 5, 2],
    "sales": [130000, 96000, 72000, 112000, 82000, 85000, 180000, 90000]
})
df

  customer     city category  quantity   sales
0     Amit  Jodhpur   Laptop         2  130000
1     Ravi   Jaipur   Mobile         3   96000
2    Priya    Delhi   Laptop         1   72000
3     Neha   Mumbai   Tablet         4  112000
4    Rahul  Jodhpur   Mobile         2   82000
5    Kiran    Delhi   Laptop         1   85000
6    Vikas   Jaipur   Tablet         5  180000
7    Pooja   Mumbai   Mobile         2   90000

## Sorting

In [63]:
df.sort_values("sales", 
               # ascending = False, 
               inplace= True
            )

In [64]:
df

  customer     city category  quantity   sales
2    Priya    Delhi   Laptop         1   72000
4    Rahul  Jodhpur   Mobile         2   82000
5    Kiran    Delhi   Laptop         1   85000
7    Pooja   Mumbai   Mobile         2   90000
1     Ravi   Jaipur   Mobile         3   96000
3     Neha   Mumbai   Tablet         4  112000
0     Amit  Jodhpur   Laptop         2  130000
6    Vikas   Jaipur   Tablet         5  180000

In [65]:
                                # ascending
df.sort_values(by = "city", ascending=False)                 # descending

  customer     city category  quantity   sales
7    Pooja   Mumbai   Mobile         2   90000
3     Neha   Mumbai   Tablet         4  112000
4    Rahul  Jodhpur   Mobile         2   82000
0     Amit  Jodhpur   Laptop         2  130000
1     Ravi   Jaipur   Mobile         3   96000
6    Vikas   Jaipur   Tablet         5  180000
2    Priya    Delhi   Laptop         1   72000
5    Kiran    Delhi   Laptop         1   85000

In [66]:
df.sort_values(["city", "sales"], ascending=[False, False])

  customer     city category  quantity   sales
3     Neha   Mumbai   Tablet         4  112000
7    Pooja   Mumbai   Mobile         2   90000
0     Amit  Jodhpur   Laptop         2  130000
4    Rahul  Jodhpur   Mobile         2   82000
6    Vikas   Jaipur   Tablet         5  180000
1     Ravi   Jaipur   Mobile         3   96000
5    Kiran    Delhi   Laptop         1   85000
2    Priya    Delhi   Laptop         1   72000

In [67]:
df.sort_index()

  customer     city category  quantity   sales
0     Amit  Jodhpur   Laptop         2  130000
1     Ravi   Jaipur   Mobile         3   96000
2    Priya    Delhi   Laptop         1   72000
3     Neha   Mumbai   Tablet         4  112000
4    Rahul  Jodhpur   Mobile         2   82000
5    Kiran    Delhi   Laptop         1   85000
6    Vikas   Jaipur   Tablet         5  180000
7    Pooja   Mumbai   Mobile         2   90000

In [68]:
df.nlargest(3, "sales")

  customer     city category  quantity   sales
6    Vikas   Jaipur   Tablet         5  180000
0     Amit  Jodhpur   Laptop         2  130000
3     Neha   Mumbai   Tablet         4  112000

In [69]:
df.nsmallest(3, "sales")

  customer     city category  quantity  sales
2    Priya    Delhi   Laptop         1  72000
4    Rahul  Jodhpur   Mobile         2  82000
5    Kiran    Delhi   Laptop         1  85000

`nlargest()` and `nsmallest()` are preferable when only a few extreme rows are needed.

## Aggregation

Common Series summaries include `sum()`, `mean()`, `median()`, `min()`, `max()`,
`count()` (non-missing values), `std()`, `var()`, and `nunique()`. Calculate
several at once:

In [70]:
df

  customer     city category  quantity   sales
2    Priya    Delhi   Laptop         1   72000
4    Rahul  Jodhpur   Mobile         2   82000
5    Kiran    Delhi   Laptop         1   85000
7    Pooja   Mumbai   Mobile         2   90000
1     Ravi   Jaipur   Mobile         3   96000
3     Neha   Mumbai   Tablet         4  112000
0     Amit  Jodhpur   Laptop         2  130000
6    Vikas   Jaipur   Tablet         5  180000

In [71]:
df["sales"].agg(["sum", "mean", "min", "max", "median"])

sum       847000.0
mean      105875.0
min        72000.0
max       180000.0
median     93000.0
Name: sales, dtype: float64

## Grouping and aggregating

`groupby()` splits rows by key, applies an aggregation to each group, and returns one result per group:

In [72]:
df

  customer     city category  quantity   sales
2    Priya    Delhi   Laptop         1   72000
4    Rahul  Jodhpur   Mobile         2   82000
5    Kiran    Delhi   Laptop         1   85000
7    Pooja   Mumbai   Mobile         2   90000
1     Ravi   Jaipur   Mobile         3   96000
3     Neha   Mumbai   Tablet         4  112000
0     Amit  Jodhpur   Laptop         2  130000
6    Vikas   Jaipur   Tablet         5  180000

In [73]:
df.groupby('city').agg(
    total_sales = ("sales", "sum"),
    avg_sales = ("sales", "mean"),
    qty_sold = ("quantity", "sum"),
)

         total_sales  avg_sales  qty_sold
city
Delhi         157000    78500.0         2
Jaipur        276000   138000.0         8
Jodhpur       212000   106000.0         4
Mumbai        202000   101000.0         6

In [74]:
df['price'] = df['sales'] / df['quantity']
df

  customer     city category  quantity   sales    price
2    Priya    Delhi   Laptop         1   72000  72000.0
4    Rahul  Jodhpur   Mobile         2   82000  41000.0
5    Kiran    Delhi   Laptop         1   85000  85000.0
7    Pooja   Mumbai   Mobile         2   90000  45000.0
1     Ravi   Jaipur   Mobile         3   96000  32000.0
3     Neha   Mumbai   Tablet         4  112000  28000.0
0     Amit  Jodhpur   Laptop         2  130000  65000.0
6    Vikas   Jaipur   Tablet         5  180000  36000.0

In [75]:
df['sales'].sum()/df['quantity'].sum()

np.float64(42350.0)

In [76]:
df.groupby("category")["sales"].agg(["sum"])

             sum
category
Laptop    287000
Mobile    268000
Tablet    292000

In [77]:
df.groupby(["city", "category"])["sales"].sum()

city     category
Delhi    Laptop      157000
Jaipur   Mobile       96000
         Tablet      180000
Jodhpur  Laptop      130000
         Mobile       82000
Mumbai   Mobile       90000
         Tablet      112000
Name: sales, dtype: int64

In [78]:
loan = pd.read_csv(r"../loan_approval_dataset_200_rows.csv")
loan.head(2)

,applicant_id,age,cibil_score,annual_income_inr,employment_type,years_employed,existing_loans,loan_amount_inr,loan_term_months,debt_to_income_ratio,loan_approved
0,APP0001,24,720,323448,Self-employed,4,2,350093,48,1.137,0
1,APP0002,51,622,1018039,Business,5,2,606816,24,0.403,1

In [79]:
loan.groupby(["employment_type", "loan_approved"]).agg(
    total_amount = ("loan_amount_inr", "sum"),
    avg_cibil_score = ("cibil_score", "mean"),
    total_applicant = ("applicant_id", "count"),
).reset_index().sort_values(by = 'total_amount', ascending= False )

,employment_type,loan_approved,total_amount,avg_cibil_score,total_applicant
2,Salaried,0,54412689,661.137931,58
3,Salaried,1,45678012,714.244898,49
4,Self-employed,0,37153953,667.864865,37
5,Self-employed,1,23973609,706.714286,21
0,Business,0,21232197,689.333333,21
1,Business,1,10160994,723.857143,14

In [80]:
loan[loan['employment_type']  == "Salaried"]["loan_amount_inr"].sum()

np.int64(100090701)

In [81]:
cibill_score_by_emp_type = loan.groupby(by ='employment_type' , as_index = False).agg({'cibil_score' : 'mean'})
cibill_score_by_emp_type

  employment_type  cibil_score
0        Business   703.142857
1        Salaried   685.457944
2   Self-employed   681.931034

In [82]:
loan.groupby(by ='employment_type' ).agg({'applicant_id' : 'count'})

                 applicant_id
employment_type
Business                   35
Salaried                  107
Self-employed              58

In [83]:
loan.groupby(by ='employment_type' ).agg({'loan_amount_inr' : 'mean'})  #

                 loan_amount_inr
employment_type
Business            8.969483e+05
Salaried            9.354271e+05
Self-employed       1.053923e+06

Use named aggregations for readable reports. Multiple keys produce a
hierarchical index; `.reset_index()` makes the keys regular columns.

In [84]:
df

  customer     city category  quantity   sales    price
2    Priya    Delhi   Laptop         1   72000  72000.0
4    Rahul  Jodhpur   Mobile         2   82000  41000.0
5    Kiran    Delhi   Laptop         1   85000  85000.0
7    Pooja   Mumbai   Mobile         2   90000  45000.0
1     Ravi   Jaipur   Mobile         3   96000  32000.0
3     Neha   Mumbai   Tablet         4  112000  28000.0
0     Amit  Jodhpur   Laptop         2  130000  65000.0
6    Vikas   Jaipur   Tablet         5  180000  36000.0

In [85]:
df

  customer     city category  quantity   sales    price
2    Priya    Delhi   Laptop         1   72000  72000.0
4    Rahul  Jodhpur   Mobile         2   82000  41000.0
5    Kiran    Delhi   Laptop         1   85000  85000.0
7    Pooja   Mumbai   Mobile         2   90000  45000.0
1     Ravi   Jaipur   Mobile         3   96000  32000.0
3     Neha   Mumbai   Tablet         4  112000  28000.0
0     Amit  Jodhpur   Laptop         2  130000  65000.0
6    Vikas   Jaipur   Tablet         5  180000  36000.0

In [86]:
kpi = (
    df.groupby("city")
    .agg(
        total_sales=("sales", "sum"),
        average_sales=("sales", "mean"),
        highest_sale=("sales", "max"),
        transactions=("sales", "count"),
        total_quantity=("quantity", "sum"),
        unique_customers=("customer", "nunique")
    )
    .reset_index()
    .sort_values("total_sales", ascending=False)
)
kpi

,city,total_sales,average_sales,highest_sale,transactions,total_quantity,unique_customers
1,Jaipur,276000,138000.0,180000,2,8,2
2,Jodhpur,212000,106000.0,130000,2,4,2
3,Mumbai,202000,101000.0,112000,2,6,2
0,Delhi,157000,78500.0,85000,2,2,2

`value_counts()` summarizes categories; `normalize=True` returns proportions:

In [87]:
loan.groupby(by = 'employment_type').agg(
    total_loan = ("loan_amount_inr", "sum"),
    avg_loan = ("loan_amount_inr", "mean"),
    loan_distribution = ("applicant_id", "count"),
)

                 total_loan      avg_loan  loan_distribution
employment_type
Business           31393191  8.969483e+05                 35
Salaried          100090701  9.354271e+05                107
Self-employed      61127562  1.053923e+06                 58

In [88]:
df["category"].value_counts()

category
Laptop    3
Mobile    3
Tablet    2
Name: count, dtype: int64

In [89]:
df

  customer     city category  quantity   sales    price
2    Priya    Delhi   Laptop         1   72000  72000.0
4    Rahul  Jodhpur   Mobile         2   82000  41000.0
5    Kiran    Delhi   Laptop         1   85000  85000.0
7    Pooja   Mumbai   Mobile         2   90000  45000.0
1     Ravi   Jaipur   Mobile         3   96000  32000.0
3     Neha   Mumbai   Tablet         4  112000  28000.0
0     Amit  Jodhpur   Laptop         2  130000  65000.0
6    Vikas   Jaipur   Tablet         5  180000  36000.0

In [90]:
loan['employment_type'].value_counts(normalize=True) * 100

employment_type
Salaried         53.5
Self-employed    29.0
Business         17.5
Name: proportion, dtype: float64

In [91]:
df["city"].value_counts(normalize=True).mul(100)  # percentage

city
Delhi      25.0
Jodhpur    25.0
Mumbai     25.0
Jaipur     25.0
Name: proportion, dtype: float64

Sort or filter grouped results as needed:

In [92]:
city_sales = df.groupby("city")["sales"].sum()
city_sales

city
Delhi      157000
Jaipur     276000
Jodhpur    212000
Mumbai     202000
Name: sales, dtype: int64

In [93]:
city_sales.sort_values(ascending=False)

city
Jaipur     276000
Jodhpur    212000
Mumbai     202000
Delhi      157000
Name: sales, dtype: int64

In [94]:
city_sales[city_sales > 200000]

city
Jaipur     276000
Jodhpur    212000
Mumbai     202000
Name: sales, dtype: int64

In [95]:
city_sales.idxmax()  # label of the largest total; max() returns the value

'Jaipur'

# Combining DataFrames

In real Data Science projects, data usually comes from **multiple tables/files**.

Main Pandas tools:

* `concat()` → stack DataFrames
* `merge()` → combine tables using a common key
* `join()` → combine mainly using index

---

## 1. `concat()` — Combine DataFrames

### Vertical Concatenation

Suppose January and February sales are stored separately:

In [96]:
import pandas as pd

jan = pd.DataFrame({
    "customer": ["Amit", "Ravi", "Priya"],
    "sales": [50000, 35000, 62000]
})
jan

  customer  sales
0     Amit  50000
1     Ravi  35000
2    Priya  62000

In [97]:

feb = pd.DataFrame({
    "customer": ["Neha", "Rahul", "Kiran"],
    "sales": [42000, 55000, 38000]
})
feb

  customer  sales
0     Neha  42000
1    Rahul  55000
2    Kiran  38000

In [98]:

sales = pd.concat([jan, feb], ignore_index=True)

sales

  customer  sales
0     Amit  50000
1     Ravi  35000
2    Priya  62000
3     Neha  42000
4    Rahul  55000
5    Kiran  38000

Output:

```text
  customer  sales
0     Amit  50000
1     Ravi  35000
2    Priya  62000
3     Neha  42000
4    Rahul  55000
5    Kiran  38000
```

### Important

In [99]:
pd.concat([jan, feb], ignore_index=True)

  customer  sales
0     Amit  50000
1     Ravi  35000
2    Priya  62000
3     Neha  42000
4    Rahul  55000
5    Kiran  38000

* `axis=0` → rows
* `axis=1` → columns
* `ignore_index=True` → creates a new index

---

# 2. `merge()` — Combine Tables Using a Key

This is extremely important in Data Analysis.

### Customers table

In [100]:
customers = pd.DataFrame({
    "customer_id": [101, 102, 103, 104],
    "customer": ["Amit", "Ravi", "Priya", "Neha"],
    "city": ["Jodhpur", "Jaipur", "Delhi", "Mumbai"]
})
customers

   customer_id customer     city
0          101     Amit  Jodhpur
1          102     Ravi   Jaipur
2          103    Priya    Delhi
3          104     Neha   Mumbai

### Orders table

In [101]:
orders = pd.DataFrame({
    "order_id": [5001, 5002, 5003, 5004, 5005],
    "customer_id": [101, 102, 101, 104, 105],
    "sales": [65000, 32000, 72000, 28000, 41000]
})
orders

   order_id  customer_id  sales
0      5001          101  65000
1      5002          102  32000
2      5003          101  72000
3      5004          104  28000
4      5005          105  41000

In [102]:
customers.merge(orders,
                how = 'left_anti'
            )

   customer_id customer   city  order_id  sales
3          103    Priya  Delhi       NaN    NaN

Customer Who Purchased Nothing

In [103]:
customers.merge(orders,
                how = 'inner'
            )

   customer_id customer     city  order_id  sales
0          101     Amit  Jodhpur      5001  65000
1          101     Amit  Jodhpur      5003  72000
2          104     Neha   Mumbai      5004  28000
3          102     Ravi   Jaipur      5002  32000

In [104]:
# customers.merge(orders,
#                 how = 'cross'
#             )

The customers who actually purchased something

In [105]:
data = {
    "transaction_id": [
        "T001", "T002", "T003", "T004", "T005",
        "T006", "T007", "T008", "T009", "T010",
        "T011", "T012", "T013", "T014", "T015"
    ],

    "customer_id": [
        "C101", "C101", "C102", "C103", "C103",
        "C104", "C104", "C105", "C101", "C106",
        "C106", "C102", "C107", "C107", "C105"
    ],

    "transaction_time": [
        "2026-10-20 10:00:00",
        "2026-10-20 10:08:00",
        "2026-10-20 11:00:00",
        "2026-10-20 12:00:00",
        "2026-10-20 12:05:00",
        "2026-10-20 13:00:00",
        "2026-10-20 13:04:00",
        "2026-10-20 14:00:00",
        "2026-10-20 10:15:00",
        "2026-10-20 15:00:00",
        "2026-10-20 15:06:00",
        "2026-10-20 11:20:00",
        "2026-10-20 16:00:00",
        "2026-10-20 16:03:00",
        "2026-10-20 14:45:00"
    ],

    "city": [
        "Delhi", "London", "Mumbai", "Jaipur", "New York",
        "Singapore", "Paris", "Jodhpur", "Dubai", "Sydney",
        "Toronto", "Mumbai", "Kolkata", "Tokyo", "Jodhpur"
    ],

    "country": [
        "India", "United Kingdom", "India", "India", "United States",
        "Singapore", "France", "India", "United Arab Emirates",
        "Australia", "Canada", "India", "India", "Japan", "India"
    ],

    "amount": [
        2500, 45000, 1200, 3500, 78000,
        8000, 65000, 900, 120000, 2200,
        95000, 1800, 1500, 85000, 1400
    ],

    "card_type": [
        "Credit", "Credit", "Debit", "Credit", "Credit",
        "Debit", "Debit", "Credit", "Credit", "Debit",
        "Debit", "Debit", "Credit", "Credit", "Credit"
    ],

    # "is_fraud": [
    #     0, 1, 0, 0, 1,
    #     0, 1, 0, 1, 0,
    #     1, 0, 0, 1, 0
    # ]
}

df = pd.DataFrame(data)

df["transaction_time"] = pd.to_datetime(df["transaction_time"])

df

,transaction_id,customer_id,transaction_time,city,country,amount,card_type
0,T001,C101,2026-10-20 10:00:00,Delhi,India,2500,Credit
1,T002,C101,2026-10-20 10:08:00,London,United Kingdom,45000,Credit
2,T003,C102,2026-10-20 11:00:00,Mumbai,India,1200,Debit
3,T004,C103,2026-10-20 12:00:00,Jaipur,India,3500,Credit
4,T005,C103,2026-10-20 12:05:00,New York,United States,78000,Credit
5,T006,C104,2026-10-20 13:00:00,Singapore,Singapore,8000,Debit
6,T007,C104,2026-10-20 13:04:00,Paris,France,65000,Debit
7,T008,C105,2026-10-20 14:00:00,Jodhpur,India,900,Credit
8,T009,C101,2026-10-20 10:15:00,Dubai,United Arab Emirates,120000,Credit
9,T010,C106,2026-10-20 15:00:00,Sydney,Australia,2200,Debit
10,T011,C106,2026-10-20 15:06:00,Toronto,Canada,95000,Debit
11,T012,C102,2026-10-20 11:20:00,Mumbai,India,1800,Debit
12,T013,C107,2026-10-20 16:00:00,Kolkata,India,1500,Credit
13,T014,C107,2026-10-20 16:03:00,Tokyo,Japan,85000,Credit
14,T015,C105,2026-10-20 14:45:00,Jodhpur,India,1400,Credit

In [106]:
crdf = df.merge(df, how = 'cross')
crdf[(crdf["customer_id_x"] ==crdf["customer_id_y"]) & (crdf["country_x"] !=crdf["country_y"]) & (crdf["transaction_id_x"] <crdf["transaction_id_y"])]

,transaction_id_x,customer_id_x,transaction_time_x,city_x,country_x,amount_x,card_type_x,transaction_id_y,customer_id_y,transaction_time_y,city_y,country_y,amount_y,card_type_y
1,T001,C101,2026-10-20 10:00:00,Delhi,India,2500,Credit,T002,C101,2026-10-20 10:08:00,London,United Kingdom,45000,Credit
8,T001,C101,2026-10-20 10:00:00,Delhi,India,2500,Credit,T009,C101,2026-10-20 10:15:00,Dubai,United Arab Emirates,120000,Credit
23,T002,C101,2026-10-20 10:08:00,London,United Kingdom,45000,Credit,T009,C101,2026-10-20 10:15:00,Dubai,United Arab Emirates,120000,Credit
49,T004,C103,2026-10-20 12:00:00,Jaipur,India,3500,Credit,T005,C103,2026-10-20 12:05:00,New York,United States,78000,Credit
81,T006,C104,2026-10-20 13:00:00,Singapore,Singapore,8000,Debit,T007,C104,2026-10-20 13:04:00,Paris,France,65000,Debit
145,T010,C106,2026-10-20 15:00:00,Sydney,Australia,2200,Debit,T011,C106,2026-10-20 15:06:00,Toronto,Canada,95000,Debit
193,T013,C107,2026-10-20 16:00:00,Kolkata,India,1500,Credit,T014,C107,2026-10-20 16:03:00,Tokyo,Japan,85000,Credit

Both tables have:

```text
customer_id
```

So we can merge them.

---

## 3. Inner Join

In [107]:
result = customers.merge(
    orders,
    on="customer_id",
    how="inner",

)

result

   customer_id customer     city  order_id  sales
0          101     Amit  Jodhpur      5001  65000
1          101     Amit  Jodhpur      5003  72000
2          104     Neha   Mumbai      5004  28000
3          102     Ravi   Jaipur      5002  32000

Only matching `customer_id` values are returned.

```text
customer_id customer      city  order_id  sales
101         Amit          Jodhpur   5001   65000
102         Ravi          Jaipur    5002   32000
101         Amit          Jodhpur   5003   72000
104         Neha          Mumbai    5004   28000
```

`105` is not present in `customers`, so it is excluded.

---

# 4. Left Join

In [108]:
result = customers.merge(
    orders,
    on="customer_id",
    how="left"
)

**All customers are preserved.**

If a customer has no order, Pandas gives `NaN`.

Useful question:

> Show me every customer, even customers who have never purchased.

---

# 5. Right Join

In [109]:
result = customers.merge(
    orders,
    on="customer_id",
    how="right"
)

All records from `orders` are preserved.

Useful when the **right DataFrame is your main dataset**.

---

# 6. Outer Join

In [110]:
result = customers.merge(
    orders,
    on="customer_id",
    how="outer"
)
result

   customer_id customer     city  order_id    sales
0          101     Amit  Jodhpur    5001.0  65000.0
1          101     Amit  Jodhpur    5003.0  72000.0
2          102     Ravi   Jaipur    5002.0  32000.0
3          103    Priya    Delhi       NaN      NaN
4          104     Neha   Mumbai    5004.0  28000.0
5          105      NaN      NaN    5005.0  41000.0

Keeps everything from both tables.

This is useful for finding:

* Customers without orders
* Orders without valid customers
* Missing relationships

---

# 7. `indicator=True`

Very useful for data auditing.

In [111]:
result = customers.merge(
    orders,
    on="customer_id",
    how="outer",
    indicator=True
)

result

   customer_id customer     city  order_id    sales      _merge
0          101     Amit  Jodhpur    5001.0  65000.0        both
1          101     Amit  Jodhpur    5003.0  72000.0        both
2          102     Ravi   Jaipur    5002.0  32000.0        both
3          103    Priya    Delhi       NaN      NaN   left_only
4          104     Neha   Mumbai    5004.0  28000.0        both
5          105      NaN      NaN    5005.0  41000.0  right_only

Pandas creates:

```text
_merge
```

Possible values:

```text
left_only
right_only
both
```

You can then find unmatched records:

In [112]:
result[result["_merge"] != "both"]

   customer_id customer   city  order_id    sales      _merge
3          103    Priya  Delhi       NaN      NaN   left_only
5          105      NaN    NaN    5005.0  41000.0  right_only

---

# 8. Merge on Multiple Columns

Sometimes one column is not enough to identify a record.

In [113]:
sales

  customer  sales
0     Amit  50000
1     Ravi  35000
2    Priya  62000
3     Neha  42000
4    Rahul  55000
5    Kiran  38000

Multiple keys:

In [114]:
on=["product_id", "city"]

---

# 9. Different Column Names

Suppose one table has:

```text
customer_id
```

and another has:

```text
cust_id
```

Use:

In [115]:
# result = customers.merge(
#     orders,
#     left_on="customer_id",
#     right_on="cust_id",
#     how="left"
# )

---

# 10. Duplicate Column Names

Suppose both tables contain:

```text
city
```

Pandas automatically creates suffixes.

You can control them:

In [116]:
df1 = pd.read_csv('df1.csv')
df1

   customer_id   name     city
0          101   Amit   Jaipur
1          102  Priya    Delhi
2          103  Rahul   Mumbai
3          104   Neha     Pune
4          105  Karan  Jodhpur

In [117]:
df2 = pd.read_csv('df2.csv')
df2

   customer_id         name order_amount
0          101  Amit Sharma        2,500
1          102  Priya Verma        1,800
2          103  Rahul Singh        3,200
3          106        Sneha        4,000
4          107        Mohit        1,200

In [118]:
result = df1.merge(
    df2,
    on="customer_id",
    suffixes=("_customer", "_order")
)
result

   customer_id name_customer    city   name_order order_amount
0          101          Amit  Jaipur  Amit Sharma        2,500
1          102         Priya   Delhi  Priya Verma        1,800
2          103         Rahul  Mumbai  Rahul Singh        3,200

Result:

```text
city_customer
city_order
```

---

# 11. `validate()` — Production Data Checking

This is very useful in real projects.

If each customer should appear only once in `customers`:

In [119]:
customers

   customer_id customer     city
0          101     Amit  Jodhpur
1          102     Ravi   Jaipur
2          103    Priya    Delhi
3          104     Neha   Mumbai

In [120]:
customers.loc[3, "customer_id"] = 101

In [121]:
orders

   order_id  customer_id  sales
0      5001          101  65000
1      5002          102  32000
2      5003          101  72000
3      5004          104  28000
4      5005          105  41000

In [122]:
# result = customers.merge(
#     orders,
#     on="customer_id",
#     # how="left",
#     validate="one_to_many"
# )
# result

Meaning:

```text
Many orders → One customer
```

If the relationship is wrong, Pandas raises an error instead of silently producing incorrect data.

---

# 12. `join()`

`join()` is commonly used when working with indexes.

In [123]:
customer_info = pd.DataFrame({
    "customer": ["Amit", "Ravi", "Priya"]
}, index=[101, 102, 103])
customer_info

    customer
101     Amit
102     Ravi
103    Priya

In [131]:

sales = pd.DataFrame({
    "sales": [65000, 32000, 72000]
}, index=[101, 102, 104])
sales

     sales
101  65000
102  32000
104  72000

In [133]:

result = sales.join(customer_info)
result

     sales customer
101  65000     Amit
102  32000     Ravi
104  72000      NaN

Output:

```text
     customer  sales
101  Amit      65000
102  Ravi      32000
103  Priya     72000
```

---

## `concat()` vs `merge()` vs `join()`

| Method     | Main Purpose               |
| ---------- | -------------------------- |
| `concat()` | Stack/append DataFrames    |
| `merge()`  | Combine using columns/keys |
| `join()`   | Combine mainly using index |

### Simple rule

```text
Same structure?
      ↓
   concat()

Different tables + common ID?
      ↓
    merge()

Index-based combination?
      ↓
     join()
```

---

## Important Real-World Pitfall

Suppose:

In [126]:
customers

   customer_id customer     city
0          101     Amit  Jodhpur
1          102     Ravi   Jaipur
2          103    Priya    Delhi
3          101     Neha   Mumbai

has one row per customer.

But:

In [127]:
orders

   order_id  customer_id  sales
0      5001          101  65000
1      5002          102  32000
2      5003          101  72000
3      5004          104  28000
4      5005          105  41000

has multiple orders per customer.

Then:

In [128]:
customers.merge(orders, on="customer_id")

   customer_id customer     city  order_id  sales
0          101     Amit  Jodhpur      5001  65000
1          101     Amit  Jodhpur      5003  72000
2          102     Ravi   Jaipur      5002  32000
3          101     Neha   Mumbai      5001  65000
4          101     Neha   Mumbai      5003  72000

will create **multiple rows for customers having multiple orders**.

This is normally correct for a one-to-many relationship, but you should always check the row count after a merge.

### Practical check

In [129]:
print("Before:", len(customers))

result = customers.merge(
    orders,
    on="customer_id",
    how="left"
)

print("After:", len(result))

Before: 4
After: 6

This helps detect unexpected row multiplication.

---

### Module 7 Keywords

```text
concat()
merge()
join()
inner join
left join
right join
outer join
on=
left_on=
right_on=
suffixes=
indicator=True
validate=
one-to-one
one-to-many
many-to-one
```