# Date & Time in Pandas

Date and time data is very common in **sales, finance, healthcare, web analytics, IoT, and transaction datasets**.

We will cover:

1. `pd.to_datetime()`
2. Extracting year, month, day
3. Date filtering
4. Date arithmetic
5. Date ranges
6. Resampling

---

## 12.1 Creating Date Data

In [6]:
import pandas as pd

df = pd.DataFrame({
    "Date": [
        "2026-01-10",
        "2026-02-15",
        "2026-03-20",
        "2026-04-25"
    ],
    "Sales": [50000, 60000, 75000, 90000]
})
df

         Date  Sales
0  2026-01-10  50000
1  2026-02-15  60000
2  2026-03-20  75000
3  2026-04-25  90000

Initially, `Date` may be stored as a string.

Check:

In [ ]:
print(df.dtypes)

Output:

```text
Date     object
Sales     int64
dtype: object
```

Convert it to datetime:

In [7]:
df["Date"] = pd.to_datetime(df["Date"])
df

        Date  Sales
0 2026-01-10  50000
1 2026-02-15  60000
2 2026-03-20  75000
3 2026-04-25  90000

Now:

In [11]:
df["Date"].dt.month_name()

0     January
1    February
2       March
3       April
Name: Date, dtype: str

Output:

```text
Date     datetime64[ns]
Sales             int64
dtype: object
```

---

# 12.2 Extract Year, Month and Day

Once the column is datetime:

### Year

In [12]:
df["Year"] = df["Date"].dt.year

### Month

In [13]:
df["Month"] = df["Date"].dt.month

### Day

In [14]:
df["Day"] = df["Date"].dt.day

### Day Name

In [15]:
df["Day_Name"] = df["Date"].dt.day_name()

### Month Name

In [16]:
df["Month_Name"] = df["Date"].dt.month_name()

Example:

In [17]:
df

        Date  Sales  Year  Month  Day  Day_Name Month_Name
0 2026-01-10  50000  2026      1   10  Saturday    January
1 2026-02-15  60000  2026      2   15    Sunday   February
2 2026-03-20  75000  2026      3   20    Friday      March
3 2026-04-25  90000  2026      4   25  Saturday      April

Output:

```text
        Date  Sales  Year  Month  Day Day_Name Month_Name
0 2026-01-10  50000  2026      1   10 Saturday    January
1 2026-02-15  60000  2026      2   15 Sunday   February
2 2026-03-20  75000  2026      3   20 Friday      March
3 2026-04-25  90000  2026      4   25 Saturday    April
```

---

# 12.3 Date Filtering

Suppose we want records after March 1:

In [20]:
result = df[df["Date"] > "2026-03-01"]

result["Sales"]

2    75000
3    90000
Name: Sales, dtype: int64

Output:

```text
        Date  Sales
2 2026-03-20  75000
3 2026-04-25  90000
```

You can also filter a date range:

In [ ]:
result = df[
    (df["Date"] >= "2026-02-01") &
    (df["Date"] <= "2026-03-31")
]

---

# 12.4 Using `.dt`

The `.dt` accessor provides many useful datetime operations.

| Operation   | Code                               |
| ----------- | ---------------------------------- |
| Year        | `df["Date"].dt.year`               |
| Month       | `df["Date"].dt.month`              |
| Day         | `df["Date"].dt.day`                |
| Day name    | `df["Date"].dt.day_name()`         |
| Month name  | `df["Date"].dt.month_name()`       |
| Day of week | `df["Date"].dt.dayofweek`          |
| Quarter     | `df["Date"].dt.quarter`            |
| Week        | `df["Date"].dt.isocalendar().week` |

---

# 12.5 Date Arithmetic

You can add or subtract time using `pd.Timedelta`.

In [21]:
df

        Date  Sales  Year  Month  Day  Day_Name Month_Name
0 2026-01-10  50000  2026      1   10  Saturday    January
1 2026-02-15  60000  2026      2   15    Sunday   February
2 2026-03-20  75000  2026      3   20    Friday      March
3 2026-04-25  90000  2026      4   25  Saturday      April

In [22]:
df["Next_Week"] = df["Date"] + pd.Timedelta(days=7)
df

        Date  Sales  Year  Month  Day  Day_Name Month_Name  Next_Week
0 2026-01-10  50000  2026      1   10  Saturday    January 2026-01-17
1 2026-02-15  60000  2026      2   15    Sunday   February 2026-02-22
2 2026-03-20  75000  2026      3   20    Friday      March 2026-03-27
3 2026-04-25  90000  2026      4   25  Saturday      April 2026-05-02

Subtract 30 days:

In [25]:
df["Previous_Month"] = df["Date"] - pd.Timedelta(days=30)
df

,Date,Sales,Year,Month,Day,Day_Name,Month_Name,Next_Week,Previous_Month
0,2026-01-10,50000,2026,1,10,Saturday,January,2026-01-17,2025-12-11
1,2026-02-15,60000,2026,2,15,Sunday,February,2026-02-22,2026-01-16
2,2026-03-20,75000,2026,3,20,Friday,March,2026-03-27,2026-02-18
3,2026-04-25,90000,2026,4,25,Saturday,April,2026-05-02,2026-03-26

---

# 12.6 Creating Date Ranges

`pd.date_range()` generates a sequence of dates.

In [28]:
dates = pd.date_range(
    start="2026-01-01",
    end="2026-01-10"
)

dates

DatetimeIndex(['2026-01-01', '2026-01-02', '2026-01-03', '2026-01-04',
               '2026-01-05', '2026-01-06', '2026-01-07', '2026-01-08',
               '2026-01-09', '2026-01-10'],
              dtype='datetime64[us]', freq='D')

You can specify frequency:

In [ ]:
dates = pd.date_range(
    start="2026-01-01",
    periods=5,
    freq="D"
)

Output:

```text
2026-01-01
2026-01-02
2026-01-03
2026-01-04
2026-01-05
```

Common frequencies:

| Frequency | Meaning     |
| --------- | ----------- |
| `D`       | Daily       |
| `W`       | Weekly      |
| `ME`      | Month end   |
| `MS`      | Month start |
| `QE`      | Quarter end |
| `YE`      | Year end    |
| `h`       | Hourly      |
| `min`     | Minute      |

---

# 12.7 Resampling

**Resampling** means changing the frequency of time-series data.

For example:

```text
Daily Sales
     ↓
Monthly Sales
```

Example:

In [36]:
# df = pd.DataFrame({
#     "Date": pd.date_range("2026-01-01", periods=90, freq="5ME"),
#     "Sales": range(100, 190)
# })

# df = df.set_index("Date")
# df

Now calculate monthly sales:

In [ ]:
monthly_sales = df["Sales"].resample("ME").sum()

print(monthly_sales)

This converts:

```text
Daily Data
    ↓
Monthly Data
```

For monthly average:

In [ ]:
monthly_avg = df["Sales"].resample("ME").mean()

For monthly maximum:

In [ ]:
monthly_max = df["Sales"].resample("ME").max()

---

## Important Real-World Pattern

A typical sales-analysis workflow is:

In [ ]:
df["Date"] = pd.to_datetime(df["Date"])

df = df.set_index("Date")

monthly_sales = (
    df["Sales"]
    .resample("ME")
    .sum()
)

print(monthly_sales)

This pattern is extremely useful for **monthly revenue reports, financial analysis, website traffic, transactions, and business dashboards**.

### Keywords Recap

```text
Date & Time
├── pd.to_datetime()
├── .dt.year
├── .dt.month
├── .dt.day
├── .dt.day_name()
├── Date Filtering
├── pd.Timedelta
├── pd.date_range()
├── set_index()
└── resample()
```